"""
Django settings for deploy project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from environs import Env

env = Env()
env.read_env()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

DOCKER_BASE_DIR = Path('/var/dmh')

from .base import *
from .static import *
from .media import *
from .deploy import *



# These will need to be adjusted upon deployment
# HTTPS = False
# HOSTNAME = 'localhost:8000'

