from . import Path
from . import BASE_DIR

DEPLOY_START_PORT = 8000

DEPLOY_DATA_ROOT = BASE_DIR / 'deploydata'

DEPLOY_VOL_ROOT = DEPLOY_DATA_ROOT / 'volumes'
DEPLOY_COMPOSE_ROOT = DEPLOY_DATA_ROOT / 'compose'
