# Generated by Django 5.1.4 on 2024-12-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_alter_gunicorn_options_alter_postgres_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='modified',
            field=models.BooleanField(default=False, help_text='Deployment settings have been modified, but the deployed Docker Compose stack has not been restarted.', null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='online',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
