# Generated by Django 5.1.4 on 2024-12-22 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_alter_volume_host_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='database',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deploy.postgres'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='sgi_server',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deploy.gunicorn'),
        ),
    ]
