# Generated by Django 5.1.4 on 2024-12-22 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_allow_blank_and_null_gunicorn_postgres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgres',
            name='name',
        ),
        migrations.RemoveField(
            model_name='postgres',
            name='password',
        ),
        migrations.RemoveField(
            model_name='postgres',
            name='username',
        ),
        migrations.AlterField(
            model_name='gunicorn',
            name='database',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='deploy.postgres'),
        ),
    ]
