# Generated by Django 5.1.4 on 2025-01-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_remove_deployment_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='mode',
            field=models.CharField(choices=[('default', 'Read/write (default)'), ('rw', 'Read/write (explicit)'), ('ro', 'Read-only')], default='default', max_length=10),
        ),
    ]
