# Generated by Django 5.1.4 on 2024-12-19 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('sites', '0004_alter_site_description_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='associated_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
