# Generated by Django 5.1.4 on 2024-12-23 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_associated_site_and_more'),
        ('sites', '0006_alter_site_deployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='associated_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
