# Generated by Django 5.1.4 on 2025-01-03 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_associated_site'),
        ('sites', '0006_alter_site_deployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='associated_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site'),
        ),
    ]
