services:
  traefik: 
    container_name: traefik
    image: traefik:v3.1
    command:
      - --api.insecure=true
      - --providers.docker
      - --log.level=INFO
      # - --providers.docker.exposedByDefault=false
      - --accessLog
    ports:
      - "80:80"     # listen port
      - "8080:8080" # web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik


networks:
  traefik: 
    name: traefik