# Generated by Django 5.1.4 on 2024-12-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='use_bundled_db',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
