# Generated by Django 5.1.4 on 2024-12-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_description_site_use_bundled_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='description_brief',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
