# Generated by Django 5.1.4 on 2024-12-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_site_description_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description_brief',
            field=models.TextField(max_length=500, null=True, verbose_name='brief description'),
        ),
    ]
