# Generated by Django 5.1.4 on 2024-12-22 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_alter_gunicorn_options_alter_postgres_options'),
        ('sites', '0004_alter_site_description_brief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='path',
        ),
        migrations.RemoveField(
            model_name='site',
            name='remote_repo',
        ),
        migrations.RemoveField(
            model_name='site',
            name='use_bundled_db',
        ),
        migrations.AddField(
            model_name='site',
            name='deployment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='deploy.deployment'),
        ),
    ]
